import type { ProjectMetadata, ProjectPayload } from "@/services/generationClient";
import { ProjectCard } from "./ProjectCard";

export function RecentProjects({ projects, loading, error, onOpen, onDelete, onCancel, onRename, onDuplicate, onPatch, deletingProjectId, cancellingProjectId }: {
  projects: ProjectPayload[]; loading?: boolean; error?: string | null; onOpen: (id: string) => void; onDelete: (project: ProjectPayload) => void | Promise<void>; onCancel: (project: ProjectPayload) => void | Promise<void>; onRename: (project: ProjectPayload) => void | Promise<void>; onDuplicate: (project: ProjectPayload) => void | Promise<void>; onPatch: (project: ProjectPayload, patch: Partial<ProjectMetadata>) => void | Promise<void>; deletingProjectId: string | null; cancellingProjectId: string | null;
}) {
  if (error) return <section className="px-5 py-8 sm:px-8"><p className="rounded-lg bg-[var(--danger-soft)] p-4 text-sm text-[var(--danger)]">{error}</p></section>;
  if (loading) return <section className="mx-auto grid max-w-[1500px] grid-cols-1 gap-5 px-5 py-8 sm:grid-cols-2 sm:px-8 xl:grid-cols-3">{[0, 1, 2].map((item) => <div key={item} className="h-80 animate-pulse rounded-2xl bg-[var(--surface)]" />)}</section>;
  if (!projects.length) return <section className="mx-auto max-w-[1500px] px-5 py-12 sm:px-8"><div className="rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface)] px-8 py-16 text-center"><h2 className="text-lg font-semibold text-[var(--text)]">No hay activos en esta vista</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Creá un activo o ajustá los filtros para verlo aquí.</p></div></section>;
  return <section className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold text-[var(--text)]">Biblioteca <span className="ml-1 text-sm font-normal text-[var(--text-secondary)]">{projects.length}</span></h2><p className="text-xs text-[var(--text-secondary)]">Ordenado por modificación reciente</p></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-3">{projects.map((project) => <ProjectCard key={project.id} project={project} onOpen={onOpen} onDelete={onDelete} onCancel={onCancel} onRename={onRename} onDuplicate={onDuplicate} onPatch={onPatch} isDeleting={deletingProjectId === project.id} isCancelling={cancellingProjectId === project.id} />)}</div></section>;
}
